// @ts-nocheck
/**
 * The exported normaliser — abofs/stonyx-orm#270.
 *
 * This file owns the criteria that do not need a live router:
 *
 *   AC-1  a consumer can `import { normalizeRecordId } from '@stonyx/orm'`,
 *         resolved through the package `exports` map, from a directory outside
 *         the repo, against the PACKED artifact. At HEAD all three reachable
 *         spellings (`@stonyx/orm/orm-request`, `.../src/orm-request.js`,
 *         `.../dist/orm-request.js`) returned ERR_PACKAGE_PATH_NOT_EXPORTED
 *         while `src/orm-request.ts` shipped in the tarball — the consumer
 *         could READ getId and could not IMPORT it, which is what forced the
 *         hand-copies.
 *
 *   the contract corpus — every spelling in the alias table, pinned to its
 *         exact value. This is the assertion set that dies when the normaliser
 *         itself changes meaning, which is the half the behavioural tests
 *         deliberately cannot see: once both sides share one implementation, a
 *         permissive edit moves them TOGETHER and every outcome assertion stays
 *         green (that is the property #270 buys). A change of meaning is then
 *         only visible here, so it becomes a deliberate, reviewed edit rather
 *         than a silent one.
 *
 * AC-2 and AC-3 are behavioural and live in
 * test/integration/reference-access/record-id-resolution.ts (NOT `-test.ts` —
 * the filename deliberately falls outside the main glob, which boots a
 * different access directory); AC-4 and AC-5 extend the static guard in
 * test/integration/readme-sample-test.ts. Behavioural assertions are kept out
 * of that file so abofs/stonyx-orm#271 (which relocates it) cannot orphan
 * them.
 */
import QUnit from 'qunit';
import { execFile } from 'node:child_process';
import { mkdtemp, mkdir, writeFile, rm, symlink } from 'node:fs/promises';
import { readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { promisify } from 'node:util';
import { fileURLToPath } from 'node:url';
import { normalizeRecordId } from '@stonyx/orm';

const { module, test } = QUnit;

const execFileAsync = promisify(execFile);
const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');

/**
 * Every spelling in the issue's alias table, plus the string-id and boundary
 * cases, each with the value the ORM resolves the record by.
 *
 * Written out as literals rather than computed: a corpus generated by calling
 * the function under test is the vacuous form of this test — it would agree
 * with any implementation, including a lowercasing or radix-10 one.
 */
const CORPUS = [
  // The alias table from the issue body. parseInt folds all of these onto 7.
  ['7', 7, 'the exact spelling'],
  ['007', 7, 'leading zeroes'],
  ['7.0', 7, 'trailing decimal'],
  ['7.9', 7, 'fractional — parseInt truncates'],
  ['7e0', 7, 'exponent notation'],
  ['0x7', 7, 'hex — parseInt auto-detects the 0x radix, because there is NO radix argument'],
  [' 7', 7, 'leading space (the decoded form of %207)'],
  ['+7', 7, 'leading plus (the decoded form of %2B7)'],
  ['\t7', 7, 'leading tab (the decoded form of %097)'],
  ['7\n', 7, 'trailing newline (the decoded form of 7%0A)'],
  // String ids pass through untouched. This is why the `owner` model looked
  // safe and why #270's string-id reproduction was one token away.
  ['angela', 'angela', 'a string id is returned untouched'],
  ['ANGELA', 'ANGELA', 'a string id keeps its CASE — the normaliser is not case-folding'],
  ['7abc', '7abc', 'a numeric prefix on a non-numeric id is NOT folded onto 7'],
  ['0x7z', '0x7z', 'a non-numeric id that merely looks hex is returned untouched'],
  // The falsy boundary. '' rather than undefined, because store.get(key,
  // undefined) returns the whole model Map instead of a record (#167).
  ['', '', 'an empty id normalises to the empty string, never to undefined'],
];

/**
 * The FALSY numeric returns — abofs/stonyx-orm#287.
 *
 * `normalizeRecordId` returns a falsy value for more inputs than `''`, and the
 * set is not obvious from reading it: `parseInt` folds four distinct URL
 * spellings onto `0`. `0` is a legitimate record id AND it is falsy, and
 * `store.remove(key, id)` branches on truthiness (`src/store.ts`), so which
 * inputs land here decides which URLs reach a `store.remove` fall-through.
 *
 * THIS FILE DOES NOT FIX THAT, AND MUST NOT. The destruction is #287's subject
 * and is byte-identical on `origin/dev`; changing `store.remove` inside a
 * priority-critical authorization fix would put an unreviewed behaviour change
 * on the persistence path. What is pinned here is only the CONTRACT — the value
 * each spelling normalises to — so that a future "cleanup" of this function
 * cannot silently move the boundary #287 is measured against.
 *
 * Separated from CORPUS because the assertion is different: `0` and `-0` are
 * `===` each other, so the sign has to be asserted with Object.is.
 */
const FALSY_CORPUS = [
  ['0', 0, false, 'a bare zero — a legitimate record id that is ALSO falsy'],
  ['00', 0, false, 'leading zeroes fold onto 0'],
  ['-0', 0, true, 'negative zero — Object.is distinguishes it, Map key lookup does not (SameValueZero)'],
  ['0x0', 0, false, 'hex zero — parseInt has no radix, so 0x0 is read as hex and folds onto 0'],
];

/**
 * The `NaN` producers — abofs/stonyx-orm#287.
 *
 * A whitespace-only id is NOT caught by `isNaN`: `Number(' ')` is `0`, so
 * `isNaN(' ')` is FALSE and the value falls through to `parseInt(' ')`, which
 * is `NaN`. Every one of these is a plain percent-encoded address-bar request.
 *
 * `NaN` is the value a consumer cannot guard against with the documented
 * pattern — `recordId === NaN` is false by definition — which is why it is
 * pinned by name rather than left to the reader to derive. Again: the contract
 * only; #287 owns the consequence.
 */
const NAN_CORPUS = [
  [' ', 'a single space, the decoded form of /%20'],
  ['\t', 'a tab, the decoded form of /%09'],
  ['\n', 'a newline, the decoded form of /%0A'],
  ['\u00a0', 'a non-breaking space, the decoded form of /%C2%A0'],
];

module('[Unit] normalizeRecordId (#270)', function() {
  module('AC-1 — the normaliser is reachable from an installed package', function() {
    /**
     * Builds a real consumer: `npm pack` this repo, extract the tarball, and
     * resolve `@stonyx/orm` from a directory outside the repo through nothing
     * but the package `exports` map.
     *
     * The extracted package gets a node_modules symlink to this repo's, which
     * is what an `npm install` would have produced for its dependencies; the
     * CONSUMER side gets only `stonyx` and `@stonyx/orm`, so nothing the probe
     * imports can resolve by accident through the repo's own tree.
     */
    async function packAndProbe(source) {
      const root = await mkdtemp(path.join(tmpdir(), 'orm270-pack-'));

      try {
        const { stdout } = await execFileAsync('npm', ['pack', '--pack-destination', root, '--silent'], { cwd: repoRoot });
        const tarball = stdout.trim().split('\n').pop();

        await mkdir(path.join(root, 'extracted'));
        await execFileAsync('tar', ['-xzf', path.join(root, tarball), '-C', path.join(root, 'extracted')]);

        const packageDir = path.join(root, 'extracted/package');
        await symlink(path.join(repoRoot, 'node_modules'), path.join(packageDir, 'node_modules'));

        const consumer = path.join(root, 'consumer');
        await mkdir(path.join(consumer, 'node_modules/@stonyx'), { recursive: true });
        await mkdir(path.join(consumer, 'config'), { recursive: true });
        await symlink(packageDir, path.join(consumer, 'node_modules/@stonyx/orm'));
        await symlink(path.join(repoRoot, 'node_modules/stonyx'), path.join(consumer, 'node_modules/stonyx'));
        await writeFile(path.join(consumer, 'package.json'), '{"name":"orm270-consumer","type":"module","private":true}');
        await writeFile(path.join(consumer, 'config/environment.js'), 'export default { orm: { db: { mode: "memory" } } };');
        await writeFile(path.join(consumer, 'probe.mjs'), source);

        const probe = await execFileAsync(process.execPath, ['probe.mjs'], { cwd: consumer });

        return { tarball, stdout: probe.stdout };
      } finally {
        await rm(root, { recursive: true, force: true });
      }
    }

    test('`import { normalizeRecordId } from "@stonyx/orm"` resolves through the exports map from outside the repo', async function(assert) {
      // A consumer app boots Stonyx before its access classes load, so the
      // probe does too: `@stonyx/orm`'s entry point reads `stonyx/config` at
      // module scope, and that is true at HEAD as well — it is a property of
      // the package, not something this issue introduced.
      const { stdout } = await packAndProbe([
        "const { default: Stonyx } = await import('stonyx');",
        "new Stonyx((await import('./config/environment.js')).default, process.cwd());",
        "const orm = await import('@stonyx/orm');",
        'process.stdout.write(JSON.stringify({',
        "  resolved: import.meta.resolve('@stonyx/orm'),",
        '  type: typeof orm.normalizeRecordId,',
        "  hex: orm.normalizeRecordId?.('0x7') ?? null,",
        "  upper: orm.normalizeRecordId?.('ANGELA') ?? null,",
        '  control: typeof orm.thisExportDoesNotExistAndMustNotResolve,',
        '}) + String.fromCharCode(10));',
        'process.exit(0);',
      ].join('\n'));

      const result = JSON.parse(stdout.trim().split('\n').pop());

      assert.equal(result.type, 'function', '`normalizeRecordId` is a function on the public entry point');

      // Non-vacuity: prove the probe can report ABSENCE. Without this, a probe
      // that resolved nothing at all could report 'function' for anything.
      assert.equal(result.control, 'undefined', 'control — a name the package does not export reads as undefined through the same probe');

      assert.ok(
        result.resolved.endsWith('/dist/index.js'),
        `resolution went through the exports map to the built entry point — got ${result.resolved}`
      );
      assert.ok(
        !result.resolved.startsWith(`file://${repoRoot}`),
        `the module under test is the EXTRACTED TARBALL, not the working tree — got ${result.resolved}`
      );

      // The behaviour survives packing: not a stub, and not a different
      // implementation that happens to share the name.
      assert.strictEqual(result.hex, 7, "the packed normaliser folds '0x7' onto 7 — no radix");
      assert.strictEqual(result.upper, 'ANGELA', "the packed normaliser leaves 'ANGELA' untouched");
    });

    test('the built entry point re-exports it, and the tarball carries that file', async function(assert) {
      // Guards the packaging half specifically: `files` could drop `dist`, or
      // src/index.ts could stop re-exporting, and the probe above would then
      // fail with a resolution error rather than naming the cause.
      const { stdout } = await execFileAsync('npm', ['pack', '--dry-run', '--json'], { cwd: repoRoot });
      const packed = JSON.parse(stdout)[0].files.map(entry => entry.path);

      assert.ok(packed.includes('dist/index.js'), 'dist/index.js is in the tarball');
      assert.ok(packed.includes('dist/normalize-record-id.js'), 'dist/normalize-record-id.js is in the tarball');
      assert.ok(packed.includes('dist/index.d.ts'), 'dist/index.d.ts is in the tarball');

      const types = readFileSync(path.join(repoRoot, 'dist/index.d.ts'), 'utf8');
      assert.ok(/normalizeRecordId/.test(types), 'dist/index.d.ts declares normalizeRecordId, so TypeScript consumers see it too');

      // `request.recordId` is public API in JS; without this it is public API
      // in JS ONLY, and a TypeScript consumer following README's
      // `const { recordId } = request;` has to re-declare a field the
      // framework already knows — #270's own defect shape, one layer over into
      // the type surface. `./orm-request` is not in the exports map, so the
      // root barrel is the only spelling that can carry it.
      assert.ok(
        /export type \{ OrmRequest\$ as OrmAccessRequest \}/.test(types),
        'dist/index.d.ts re-exports the access() request type as OrmAccessRequest'
      );

      const requestTypes = readFileSync(path.join(repoRoot, 'dist/orm-request.d.ts'), 'utf8');

      assert.ok(/export interface OrmRequest\$/.test(requestTypes), 'dist/orm-request.d.ts EXPORTS the interface, so the re-export above resolves');
      assert.ok(/recordId\?: string \| number \| undefined/.test(requestTypes), 'and the interface declares recordId, including the undefined the collection branch depends on');
    });
  });

  module('the normaliser contract — today\'s semantics, pinned exactly', function() {
    for (const [raw, expected, why] of CORPUS) {
      test(`normalizeRecordId(${JSON.stringify(raw)}) === ${JSON.stringify(expected)} — ${why}`, function(assert) {
        const actual = normalizeRecordId(raw);

        assert.strictEqual(
          actual,
          expected,
          `${JSON.stringify(raw)} -> ${JSON.stringify(actual)} (expected ${JSON.stringify(expected)}: ${why})`
        );
        assert.strictEqual(
          typeof actual,
          typeof expected,
          `${JSON.stringify(raw)} -> ${typeof actual} (expected ${typeof expected}) — a numeric id must be a NUMBER, or a predicate comparing === against a number never matches`
        );
      });
    }

    for (const [raw, expected, isNegativeZero, why] of FALSY_CORPUS) {
      test(`normalizeRecordId(${JSON.stringify(raw)}) === ${expected} — ${why}`, function(assert) {
        const actual = normalizeRecordId(raw);

        assert.strictEqual(actual, expected, `${JSON.stringify(raw)} -> ${String(actual)} (expected ${expected}: ${why})`);
        assert.strictEqual(typeof actual, 'number', `${JSON.stringify(raw)} -> ${typeof actual}; it is a NUMBER, so a predicate comparing === against 0 matches it`);
        assert.strictEqual(Object.is(actual, -0), isNegativeZero, `${JSON.stringify(raw)} -> ${Object.is(actual, -0) ? '-0' : '+0'}`);

        // The property that makes this row load-bearing rather than trivia.
        assert.notOk(actual, `${JSON.stringify(raw)} normalises to a FALSY id — see abofs/stonyx-orm#287; not fixed here`);
      });
    }

    for (const [raw, why] of NAN_CORPUS) {
      test(`normalizeRecordId(${JSON.stringify(raw)}) is NaN — ${why}`, function(assert) {
        const actual = normalizeRecordId(raw);

        // Not strictEqual: NaN !== NaN, which is the whole point.
        assert.ok(Number.isNaN(actual), `${JSON.stringify(raw)} -> ${String(actual)} (expected NaN: ${why})`);
        assert.strictEqual(typeof actual, 'number', `${JSON.stringify(raw)} -> ${typeof actual}`);

        // Non-vacuity for the row above: this input is NOT caught by the
        // isNaN() guard inside the normaliser, which is why it reaches parseInt.
        assert.notOk(isNaN(raw), `isNaN(${JSON.stringify(raw)}) is FALSE — Number(${JSON.stringify(raw)}) is 0, so the guard does not fire and parseInt runs`);

        // Unguardable by the documented predicate — abofs/stonyx-orm#287.
        assert.notOk(actual === actual, `recordId === recordId is false for ${JSON.stringify(raw)}, so no === guard a consumer writes can ever match it`);
      });
    }

    test('control — a NaN row could have failed: an ordinary numeric id is not NaN', function(assert) {
      // Without this, `Number.isNaN(actual)` above would also pass against a
      // normaliser that returned NaN for everything.
      assert.notOk(Number.isNaN(normalizeRecordId('7')), "normalizeRecordId('7') is 7, not NaN");
      assert.notOk(Number.isNaN(normalizeRecordId('angela')), "normalizeRecordId('angela') is 'angela', not NaN");
    });

    test('an absent id normalises to the empty string, not undefined', function(assert) {
      // store.get(key, undefined) returns the whole model Map rather than a
      // record — abofs/stonyx-orm#167, pinned by
      // test/unit/store-get-falsy-id-test.ts. The '' is load-bearing on the
      // resolution path and must not be "cleaned up" to undefined.
      assert.strictEqual(normalizeRecordId(undefined), '', 'undefined -> ""');
      assert.strictEqual(normalizeRecordId(null), '', 'null -> ""');
    });

    test('the normaliser is synchronous', function(assert) {
      // auth() is called without `await` by @stonyx/rest-server
      // (dist/request.js:59). A promise here would be handed to access() as
      // the record id, and every === against it would be false — fail-open.
      const value = normalizeRecordId('7');

      assert.notOk(value instanceof Promise, 'returns a value, not a promise');
      assert.equal(typeof normalizeRecordId, 'function', 'and it is a plain function');
    });
  });
});
